export const apiconfig = {
	baseUrl: 'https://api.themoviedb.org/3',
	baseUrlImageOriginal: 'https://image.tmdb.org/t/p/original',
	baseUrlImageW500: 'https://image.tmdb.org/t/p/w500',
	baseUrlImageW300: 'https://image.tmdb.org/t/p/w300',
	baseUrlImageW92: 'https://image.tmdb.org/t/p/w92',
	pPolular: '/movie/popular',
	pValorada: '/movie/top_rated',
	pProximamente: '/movie/upcoming',
	sPopular: '/tv/popular',
	sValorada: '/tv/top_rated',
	buscarPelicula: '/search/movie',
	tendenciasPelicula: '/trending/movie/week',
	tendenciasSeries: '/trending/tv/week',
	tendenciasTodas: '/trending/all/week',
	buscarTodo: '/search/multi?query=',
	generosP: {
		accion: '/discover/movie?with_genres=28',
		animacion: '/discover/movie?with_genres=16',
		aventura: '/discover/movie?with_genres=12',
		comedia: '/discover/movie?with_genres=35',
		familia: '/discover/movie?with_genres=10751',
		misterio: '/discover/movie?with_genres=9648',
	},

	generosS: {
		accion: '/discover/tv?with_genres=10759',
		animacion: '/discover/tv?with_genres=16',
		comedia: '/discover/tv?with_genres=35',
		familia: '/discover/tv?with_genres=10751',
		misterio: '/discover/tv?with_genres=9648',
	},
}
