export const apiconfig = {
	baseUrl: 'https://api.themoviedb.org/3',
	baseUrlImageOriginal: 'https://image.tmdb.org/t/p/original',
	baseUrlImageW500: 'https://image.tmdb.org/t/p/w500',
	baseUrlImageW300: 'https://image.tmdb.org/t/p/w300',
	baseUrlImageW92: 'https://image.tmdb.org/t/p/w92',
	pPolular: '/movie/popular',
	pValorada: '/movie/top_rated',
	pProximamente: '/movie/upcoming',
	sPopular: '/tv/popular',
	sValorada: '/tv/top_rated',
	buscarPelicula: '/search/movie',
	tendenciasPelicula: '/trending/movie/week',
	tendenciasSeries: '/trending/tv/week',
	tendenciasTodas: '/trending/all/week',
	sAccion: '/search/tv?query=',
	pAccion: '/search/movie?query=',
	buscarTodo: '/search/multi?query=',
}
